# Name: Update Sitemap
# YML file path: .github/workflows/update-sitemap.yml

name: Update Sitemap

on:
  schedule:
    # Hourly run (Har ghante sitemap update hoga)
    - cron: '0 * * * *' 
  workflow_dispatch:

jobs:
  build-sitemap:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Install dependencies
        # node-fetch version 2 is required for CommonJS in older Node environments
        run: npm install node-fetch@2
      - name: Generate sitemap
        # JS file scripts folder mein hona chahiye
        run: node scripts/generate-sitemap.js
      - name: Commit & Push
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          # ✅ Corrected Path: sitemap.xml ko root folder mein commit karo
          git add sitemap.xml
          git commit -m "Auto-update sitemap [skip ci]" || echo "No changes"
          git push
          
