name: Update Sitemap

on:
  schedule:
    - cron: '0 * * * *' # every hour
  workflow_dispatch:

jobs:
  build-sitemap:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install node-fetch@2

      - name: Generate sitemap
        env:
          SHEET_KEY: ${{ secrets.GOOGLE_SHEET_API_KEY }}
        run: |
          set -e
          node scripts/generate-sitemap.js

      - name: Commit & Push Sitemap
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add -f public/sitemap.xml public/_headers
          TIMESTAMP=$(date -u +%Y-%m-%dT%H:%M:%SZ)
          git commit -m "Auto-update sitemap: ${TIMESTAMP}" || echo "No changes"
          git push

      - name: Trigger Cloudflare Pages Deployment
        env:
          CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CF_ACCOUNT_ID: '1de9700c63c35247d84a4caaf3700f6b'
          CF_PAGES_PROJECT: 'Adulthub'
        run: |
          curl -X POST "https://api.cloudflare.com/client/v4/accounts/${CF_ACCOUNT_ID}/pages/projects/${CF_PAGES_PROJECT}/deployments" \
          -H "Authorization: Bearer ${CLOUDFLARE_TOKEN}" \
          -H "Content-Type: application/json" \
          --data '{"branch": "main"}'

      - name: Purge Cloudflare Cache
        run: |
          curl -X POST "https://api.cloudflare.com/client/v4/zones/${{ secrets.CLOUDFLARE_ZONE_ID }}/purge_cache" \
          -H "Authorization: Bearer ${{ secrets.CLOUDFLARE_API_TOKEN }}" \
          -H "Content-Type: application/json" \
          --data '{"files":["https://dareloom.fun/sitemap.xml"]}'
