# Name: Update Sitemap
# YML file path: .github/workflows/update-sitemap.yml

name: Update Sitemap

on:
  schedule:
    - cron: '0 * * * *' # हर घंटे
  workflow_dispatch:

jobs:
  build-sitemap:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        # node-fetch version 2.6.7 is required as per your package.json
        run: npm install node-fetch@2.6.7

      - name: Generate sitemap (This runs the script)
        env:
          SHEET_KEY: ${{ secrets.GOOGLE_SHEET_API_KEY }}
        run: node scripts/generate-sitemap.js

      - name: Commit & Push Sitemap
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
          # Force add both the sitemap and the headers file
          git add -f public/sitemap.xml public/_headers
          
          TIMESTAMP=$(date -u +%Y-%m-%dT%H:%M:%SZ)
          git commit -m "Auto-update sitemap: ${TIMESTAMP}" || echo "No changes"
          git push

      - name: Trigger Cloudflare Pages Deployment
        env:
          CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CF_ACCOUNT_ID: '1de9700c63c35247d84a4caaf3700f6b'
          CF_PAGES_PROJECT: 'Adulthub'
        run: |
          curl -X POST "https://api.cloudflare.com/client/v4/accounts/${CF_ACCOUNT_ID}/pages/projects/${CF_PAGES_PROJECT}/deployments" \
          -H "Authorization: Bearer ${CLOUDFLARE_TOKEN}" \
          -H "Content-Type: application/json" \
          --fail \
          --data '{"branch": "main"}'

      # This is the most critical step for cache issues
      - name: Purge Cloudflare Cache (Requires CLOUDFLARE_ZONE_ID secret)
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
        run: |
          if [ -z "$CLOUDFLARE_ZONE_ID" ]; then
            echo "CLOUDFLARE_ZONE_ID is not set. Skipping cache purge."
            exit 0
          fi
          
          echo "Purging Cloudflare cache for sitemap.xml..."
          curl -X POST "https://api.cloudflare.com/client/v4/zones/${CLOUDFLARE_ZONE_ID}/purge_cache" \
          -H "Authorization: Bearer ${CLOUDFLARE_API_TOKEN}" \
          -H "Content-Type: application/json" \
          --fail \
          --silent \
          --show-error \
          --data '{"files":["https://dareloom.fun/sitemap.xml"]}'
          
